### ISSUE TITLE
Divide demo and component code

### ISSUE THREAD

**Issue by janis-kra** [enpit/chateau-bouble#1]
In order to release this as a reusable react component, we have to remove the demo code from this repo (and repurpose it for a demo repo)

**Comment by objectliteral** [comment]
I think we can not get around having some demo code in this repo directly, because we need to test our changes to the UI. If we were to `npm publish` and `npm install` it everytime we want to try something out, that would be a huge hassle.

But I still think, we should use a separate repo to contain a more presentable demo, more like a project homepage.

**Comment by janis-kra** [comment]
can't we just use `npm link` for that?

**Comment by janis-kra** [comment]
We currently have an issue with loading the stylesheets that styled-components generates, which arises when two instances of the SC lib are loaded (i.e. when the client application also uses SC). Will hopefully be fixed soon via https://github.com/styled-components/styled-components/pull/1102

In the meantime we can just remove any SC code from the demo application in order to have a working demo app

**Comment by objectliteral** [comment]
I moved the whole project from CRA to nwb, which IMO offers a slightly nicer seperation of demo-code and the component code itself.

Currently, the build will be missing one of our CSS files. I will either move the styles into the component or find a way to include the CSS file into the build. Whatever will turn out to be easier.

Apart from that, I'm still not satisfied with how much magic our stack includes. I might experiment a bit with setting up the most important infrastructure myself without relying on magical tools like CRA or nwb.
